language: node_js
node_js:
  - '8'
  - '10'
  - 'node'
cache: npm
notifications:
  email: false
before_install:
  - npm install -g codecov
script:
  - npm run lint
  - npm run test
  - codecov
branches:
  except:
    - '/^v\d+\.\d+\.\d+$/'
jobs:
  include:
    - stage: deploy
      if: branch == master
      node_js: '10' # pre-installed version
      script:
        - npm install -g semantic-release@^15
        - semantic-release
